### PR TITLE
Dockerization setup

### LINKED ISSUE #2: Containerize the application
Setup a basic docker stack to build and containerize Nikel images. Would make it much safer and easier to deploy on a number of platforms.

### PR DESCRIPTION
**Pull request by bill-ahmed**
Includes docker configurations for running the app inside a container. There is also a new GitHub action that builds & pushes a new image to [docker hub](https://hub.docker.com/) whenever a push is made to the `master` branch.

The GitHub action will currently fail, until the relevant repository and credentials are created via docker hub. To do so:
1. Create a new account on docker hub (or login if you already have one)
2. Go to https://hub.docker.com/settings/security
3. Generate a new Access Token
4. Follow the instructions [here](https://docs.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets) to setup the relevant GitHub secrets for `DOCKER_USERNAME` and `DOCKER_PASSWORD`
5. Update the `repository` value under the workflow `docker-image-build-and-push.yml`

I've also updated the README for instructions on how to deploy the container.

Resolves #2.

### CODE REVIEW

**Comment by bill-ahmed** [comment]
I would hold off on merging until docker hub is configured.

**Comment by darenliang** [comment]
Thanks for the pull request!

I would recommend not using GitHub actions and use Docker Hub's native solution instead.

Could you make a Docker Hub account so I can add you as an org member?

**Comment by bill-ahmed** [comment]
Sure thing, my docker hub username is `billahmed`. And yea I'll remove the workflow from this PR.

**Comment by bill-ahmed** [comment]
Removed the workflow, let me know if there's anything else I should look out for.

**Comment by darenliang** [comment]
There are a few things that I want to point out before we merge this change:

- It would be great if the service name would be called `core` as it would automatically name the image as `nikel_core`. Also, maybe mapping the rest of the envs would be a good idea.

```
version: "3.8" # https://docs.docker.com/compose/compose-file/
services:
  core:
    container_name: nikel-core
    restart: always
    build: ./
    ports:
      - "$PORT:8080"
    environment:
      GIN_MODE: "$GIN_MODE"
      RATELIMIT: "$RATELIMIT"
```
- I believe that `go install` automatically builds the `nikel-core` binary in the root folder.

`CMD ["go", "run", "nikel-core/main.go"]` could be replaced by `ENTRYPOINT ["nikel-core"]`

- Is there any reason to have the `.dockerignore` file? Could it affect Docker Hub's ability to pull and clone the repo?

**Comment by bill-ahmed** [comment]
The `.dockerignore` should not affect how images are built or run. I added it to help keep the final image cleaner.

**Comment by darenliang** [comment]
Looks good.

**Pull request merged**
